import ROOT as rt

rt.gStyle.SetOptStat(0)


def get_width_from_kappa(kappa):
    return rt.TMath.Sqrt(-2*rt.TMath.Log(rt.TMath.BesselI1(kappa)/rt.TMath.BesselI0(kappa)))

def get_width_error_from_kappa(kappa, kappa_error):
    deriv = (rt.TMath.BesselI0(kappa)**2 + rt.TMath.BesselI0(kappa)*rt.TMath.BesselI(2, kappa) - 2*rt.TMath.BesselI1(kappa)**2)/(2*rt.TMath.Sqrt(2)*rt.TMath.BesselI0(kappa)*rt.TMath.BesselI1(kappa)*rt.TMath.Sqrt(-rt.TMath.Log(rt.TMath.BesselI1(kappa)/rt.TMath.BesselI0(kappa))))
    return deriv * kappa_error

c = rt.TCanvas('c', 'c', 800, 600)
c.SetLeftMargin(0.15)
c.SetBottomMargin(0.15)
c.SetTheta(20)
c.SetPhi(50)

BRANCHING_RATIO = 0.639

N_EVENTS_DATA = 248341207
N_EVENTS_EPOS = 29179505
N_EVENTS_DPMJET = 113981589

data_infile = rt.TFile.Open("data_infile.root")
dpmjet_infile = rt.TFile.Open("dpmjet_0_80_2d_dists_new.root")
epos_infile = rt.TFile.Open("epos_0_80_2d_dists_large_deta.root")
phsd_infile = rt.TFile.Open("phsd_out_60mil.root")
phsd_mult_dist = phsd_infile.Get("mult_dist")
N_EVENTS_PHSD = phsd_mult_dist.Integral(2, phsd_mult_dist.GetNbinsX())

trig_dist_data = data_infile.Get("trig_pt_dist_0_80")
trig_dist_dpmjet = dpmjet_infile.Get("trig_dist")
trig_dist_epos = epos_infile.Get("trig_dist")
trig_dist_phsd = phsd_infile.Get("trigger_dist")
trig_dist_phsd.Sumw2()

trig_dist_phsd.GetAxis(0).SetRangeUser(4, 7.99999)


trig_dist_dpmjet = trig_dist_dpmjet.Projection(0)
trig_dist_epos = trig_dist_epos.Projection(0)
trig_dist_phsd = trig_dist_phsd.Projection(0)
n_trigs_phsd = trig_dist_phsd.Integral(1, trig_dist_phsd.GetNbinsX())

# scale by N_EVENTS
trig_dist_data.Scale(1.0 / N_EVENTS_DATA)
trig_dist_dpmjet.Scale(1.0 / N_EVENTS_DPMJET)
trig_dist_epos.Scale(1.0 / N_EVENTS_EPOS)
trig_dist_phsd.Scale(1.0 / N_EVENTS_PHSD)
# scale by bin width
trig_dist_data.Scale(1.0 / trig_dist_data.GetBinWidth(1))
trig_dist_dpmjet.Scale(1.0 / trig_dist_dpmjet.GetBinWidth(1))
trig_dist_epos.Scale(1.0 / trig_dist_epos.GetBinWidth(1))
trig_dist_phsd.Scale(1.0 / trig_dist_phsd.GetBinWidth(1))

trig_dist_data.SetLineColor(rt.kBlack)
trig_dist_dpmjet.SetLineColor(rt.kBlue + 2)
trig_dist_epos.SetLineColor(rt.kGreen + 2)
trig_dist_phsd.SetLineColor(rt.kRed + 2)

trig_dist_data.SetLineWidth(2)
trig_dist_dpmjet.SetLineWidth(2)
trig_dist_epos.SetLineWidth(2)
trig_dist_phsd.SetLineWidth(2)

trig_dist_data.SetMarkerStyle(20)
trig_dist_dpmjet.SetMarkerStyle(20)
trig_dist_epos.SetMarkerStyle(20)
trig_dist_phsd.SetMarkerStyle(20)

trig_dist_data.SetMarkerSize(1.0)
trig_dist_dpmjet.SetMarkerSize(1.0)
trig_dist_epos.SetMarkerSize(1.0)
trig_dist_phsd.SetMarkerSize(1.0)

trig_dist_data.SetMarkerColor(rt.kBlack)
trig_dist_dpmjet.SetMarkerColor(rt.kBlue + 2)
trig_dist_epos.SetMarkerColor(rt.kGreen + 2)
trig_dist_phsd.SetMarkerColor(rt.kRed + 2)

trig_dist_data.SetTitle(";p_{T} [GeV/c];1/N_{evt} dN/dp_{T} [(GeV/c)^{-1}]")
trig_dist_data.GetYaxis().SetTitleOffset(1.5)
trig_dist_data.GetYaxis().SetRangeUser(0, 0.06)

trig_dist_data.Draw()
trig_dist_dpmjet.Draw("same")
trig_dist_epos.Draw("same")
trig_dist_phsd.Draw("same")

leg = rt.TLegend(0.6, 0.6, 0.9, 0.85)
leg.AddEntry(trig_dist_data, "Data", "lep")
leg.AddEntry(trig_dist_dpmjet, "DPMJet", "lep")
leg.AddEntry(trig_dist_epos, "EPOS-LHC", "lep")
leg.AddEntry(trig_dist_phsd, "PHSD", "lep")
leg.SetBorderSize(0)
leg.SetFillStyle(0)
leg.Draw("same")
c.Draw()
c.SaveAs("figures/trig_dist_comp.pdf")


h_h_dist_phsd = phsd_infile.Get("h_h_dist")
h_lambda_dist_phsd = phsd_infile.Get("h_lambda_dist")

h_lambda_dist_phsd.GetAxis(0).SetRangeUser(4, 7.9999)
h_lambda_dist_phsd.GetAxis(1).SetRangeUser(2, 3.9999)
h_lambda_dist_phsd.Projection(2).Draw()
c.Draw()

h_h_dist_phsd.GetAxis(0).SetRangeUser(4, 7.9999)
h_h_dist_phsd.GetAxis(1).SetRangeUser(2, 3.9999)
h_h_dist_phsd.GetAxis(3).SetRangeUser(-1.6, 1.59999)

h_lambda_dist_phsd.GetAxis(0).SetRangeUser(4, 7.9999)
h_lambda_dist_phsd.GetAxis(1).SetRangeUser(2, 3.9999)
h_lambda_dist_phsd.GetAxis(3).SetRangeUser(-1.6, 1.59999)

h_h_2d_phsd = h_h_dist_phsd.Projection(2, 3)
h_lambda_2d_phsd = h_lambda_dist_phsd.Projection(2, 3)
h_h_2d_phsd.Scale(1/n_trigs_phsd)
h_lambda_2d_phsd.Scale(1/n_trigs_phsd)

h_h_2d_phsd.RebinY(4)
h_lambda_2d_phsd.RebinY(4)


h_h_2d_data = data_infile.Get("h_h_2d_mixcor_0_80")
h_h_2d_dpmjet = dpmjet_infile.Get("h_h_2d")
h_h_2d_epos = epos_infile.Get("h_h_2d")

h_lambda_2d_data = data_infile.Get("h_lambda_2d_subtracted_0_80")
h_lambda_2d_dpmjet = dpmjet_infile.Get("h_lambda_2d")
h_lambda_2d_dpmjet.Scale(1/BRANCHING_RATIO)
h_lambda_2d_epos = epos_infile.Get("h_lambda_2d")
h_lambda_2d_epos.Scale(1/BRANCHING_RATIO)


h_h_2d_data.SetTitle("")
h_h_2d_dpmjet.SetTitle("")
h_h_2d_epos.SetTitle("")
h_h_2d_phsd.SetTitle("")
h_lambda_2d_data.SetTitle("")
h_lambda_2d_dpmjet.SetTitle("")
h_lambda_2d_epos.SetTitle("")
h_lambda_2d_phsd.SetTitle("")

h_h_2d_data.GetXaxis().SetTitle("#Delta#eta")
h_h_2d_data.GetYaxis().SetTitle("#Delta#varphi")
h_h_2d_dpmjet.GetXaxis().SetTitle("#Delta#eta")
h_h_2d_dpmjet.GetYaxis().SetTitle("#Delta#varphi")
h_h_2d_epos.GetXaxis().SetTitle("#Delta#eta")
h_h_2d_epos.GetYaxis().SetTitle("#Delta#varphi")
h_h_2d_phsd.GetXaxis().SetTitle("#Delta#eta")
h_h_2d_phsd.GetYaxis().SetTitle("#Delta#varphi")
h_lambda_2d_data.GetXaxis().SetTitle("#Delta#eta")
h_lambda_2d_data.GetYaxis().SetTitle("#Delta#varphi")
h_lambda_2d_dpmjet.GetXaxis().SetTitle("#Delta#eta")
h_lambda_2d_dpmjet.GetYaxis().SetTitle("#Delta#varphi")
h_lambda_2d_epos.GetXaxis().SetTitle("#Delta#eta")
h_lambda_2d_epos.GetYaxis().SetTitle("#Delta#varphi")
h_lambda_2d_phsd.GetXaxis().SetTitle("#Delta#eta")
h_lambda_2d_phsd.GetYaxis().SetTitle("#Delta#varphi")

h_h_2d_data.GetXaxis().SetTitleSize(0.05)
h_h_2d_data.GetYaxis().SetTitleSize(0.05)
h_h_2d_dpmjet.GetXaxis().SetTitleSize(0.05)
h_h_2d_dpmjet.GetYaxis().SetTitleSize(0.05)
h_h_2d_epos.GetXaxis().SetTitleSize(0.05)
h_h_2d_epos.GetYaxis().SetTitleSize(0.05)
h_h_2d_phsd.GetXaxis().SetTitleSize(0.05)
h_h_2d_phsd.GetYaxis().SetTitleSize(0.05)
h_lambda_2d_data.GetXaxis().SetTitleSize(0.05)
h_lambda_2d_data.GetYaxis().SetTitleSize(0.05)
h_lambda_2d_dpmjet.GetXaxis().SetTitleSize(0.05)
h_lambda_2d_dpmjet.GetYaxis().SetTitleSize(0.05)
h_lambda_2d_epos.GetXaxis().SetTitleSize(0.05)
h_lambda_2d_epos.GetYaxis().SetTitleSize(0.05)
h_lambda_2d_phsd.GetXaxis().SetTitleSize(0.05)
h_lambda_2d_phsd.GetYaxis().SetTitleSize(0.05)

h_h_2d_data.GetXaxis().SetTitleOffset(1.2)
h_h_2d_data.GetYaxis().SetTitleOffset(1.2)
h_h_2d_dpmjet.GetXaxis().SetTitleOffset(1.2)
h_h_2d_dpmjet.GetYaxis().SetTitleOffset(1.2)
h_h_2d_epos.GetXaxis().SetTitleOffset(1.2)
h_h_2d_epos.GetYaxis().SetTitleOffset(1.2)
h_h_2d_phsd.GetXaxis().SetTitleOffset(1.2)
h_h_2d_phsd.GetYaxis().SetTitleOffset(1.2)
h_lambda_2d_data.GetXaxis().SetTitleOffset(1.2)
h_lambda_2d_data.GetYaxis().SetTitleOffset(1.2)
h_lambda_2d_dpmjet.GetXaxis().SetTitleOffset(1.2)
h_lambda_2d_dpmjet.GetYaxis().SetTitleOffset(1.2)
h_lambda_2d_epos.GetXaxis().SetTitleOffset(1.2)
h_lambda_2d_epos.GetYaxis().SetTitleOffset(1.2)
h_lambda_2d_phsd.GetXaxis().SetTitleOffset(1.2)
h_lambda_2d_phsd.GetYaxis().SetTitleOffset(1.2)

h_h_2d_data.Draw("SURF1")
c.Draw()
c.SaveAs("figures/h_h_2d_data.pdf")

h_h_2d_data.ProjectionX().Draw()
c.Draw()
c.SaveAs("figures/h_h_data_deta.pdf")

h_h_2d_dpmjet.Draw("SURF1")
c.Draw()
c.SaveAs("figures/h_h_2d_dpmjet.pdf")

h_h_2d_dpmjet.ProjectionX().Draw()
c.Draw()
c.SaveAs("figures/h_h_dpmjet_deta.pdf")

h_h_2d_epos.Draw("SURF1")
c.Draw()
c.SaveAs("figures/h_h_2d_epos.pdf")

h_h_2d_epos.ProjectionX().Draw()
c.Draw()
c.SaveAs("figures/h_h_epos_deta.pdf")

h_h_2d_phsd.Draw("SURF1")
c.Draw()
c.SaveAs("figures/h_h_2d_phsd.pdf")

h_h_2d_phsd.ProjectionX().Draw()
c.Draw()
c.SaveAs("figures/h_h_phsd_deta.pdf")

h_lambda_2d_data.Draw("SURF1")
c.Draw()
c.SaveAs("figures/h_lambda_2d_data.pdf")

h_lambda_2d_dpmjet.Draw("SURF1")
c.Draw()
c.SaveAs("figures/h_lambda_2d_dpmjet.pdf")

h_lambda_2d_epos.Draw("SURF1")
c.Draw()
c.SaveAs("figures/h_lambda_2d_epos.pdf")

h_lambda_2d_phsd.Draw("SURF1")
c.Draw()
c.SaveAs("figures/h_lambda_2d_phsd.pdf")

# doing our best to get the massive flow BG for EPOS-LHC
h_h_2d_epos.GetXaxis().SetRangeUser(-1.6, -1.20001)
h_h_1d_left_deta = h_h_2d_epos.ProjectionY("h_h_1d_left_deta")
h_h_2d_epos.GetXaxis().SetRangeUser(1.2, 1.5999999)
h_h_1d_right_deta = h_h_2d_epos.ProjectionY("h_h_1d_right_deta")
h_h_1d_large_deta = h_h_1d_left_deta.Clone("h_h_1d_large_deta")
h_h_1d_large_deta.Add(h_h_1d_right_deta)
vn_fit_epos_string = "[0] + [1]*cos(2*x) + [2]*cos(4*x)"
vn_fit_epos = rt.TF1("vn_fit_epos", vn_fit_epos_string, -rt.TMath.Pi()/2, rt.TMath.Pi()/2)
vn_fit_epos_total = rt.TF1("vn_fit_epos", vn_fit_epos_string, -rt.TMath.Pi()/2, 3*rt.TMath.Pi()/2)
vn_fit_epos.SetParameter(0, 0.051)
vn_fit_epos.SetParameter(1, 0.0275)
h_h_1d_large_deta.Fit(vn_fit_epos, "R")
vn_fit_epos_total.SetParameter(0, vn_fit_epos.GetParameter(0))
vn_fit_epos_total.SetParameter(1, vn_fit_epos.GetParameter(1))
vn_fit_epos_total.SetParameter(2, vn_fit_epos.GetParameter(2))
h_h_1d_large_deta.Draw()
vn_fit_epos_total.Draw("same")
c.Draw()
c.SaveAs("figures/epos_vn_fit_epos.pdf")

# setting the dEta range back to normal
h_h_2d_epos.GetXaxis().SetRangeUser(-1.2, 1.19999)

# also looking into DPMJet (despite 0 visible flow)
h_h_2d_dpmjet.GetXaxis().SetRangeUser(-1.6, -1.20001)
h_h_1d_left_deta = h_h_2d_dpmjet.ProjectionY("h_h_1d_left_deta")
h_h_2d_dpmjet.GetXaxis().SetRangeUser(1.2, 1.5999999)
h_h_1d_right_deta = h_h_2d_dpmjet.ProjectionY("h_h_1d_right_deta")
h_h_1d_large_deta = h_h_1d_left_deta.Clone("h_h_1d_large_deta")
h_h_1d_large_deta.Add(h_h_1d_right_deta)
vn_fit_dpmjet_string = "[0] + [1]*cos(2*x) + [2]*cos(4*x)"
vn_fit_dpmjet = rt.TF1("vn_fit_dpmjet", vn_fit_dpmjet_string, -rt.TMath.Pi()/2, rt.TMath.Pi()/2)
vn_fit_dpmjet_total = rt.TF1("vn_fit_dpmjet", vn_fit_dpmjet_string, -rt.TMath.Pi()/2, 3*rt.TMath.Pi()/2)
vn_fit_dpmjet.SetParameter(0, 0.03)
vn_fit_dpmjet.FixParameter(1, 0)
vn_fit_dpmjet.FixParameter(2, 0)
h_h_1d_large_deta.Fit(vn_fit_dpmjet, "R")
vn_fit_dpmjet_total.SetParameter(0, vn_fit_dpmjet.GetParameter(0))
vn_fit_dpmjet_total.SetParameter(1, vn_fit_dpmjet.GetParameter(1))
vn_fit_dpmjet_total.SetParameter(2, vn_fit_dpmjet.GetParameter(2))
h_h_1d_large_deta.Draw()
vn_fit_dpmjet_total.Draw("same")
c.Draw()
c.SaveAs("figures/dpmjet_vn_fit_dpmjet.pdf")
# setting the dEta range back to normal
h_h_2d_dpmjet.GetXaxis().SetRangeUser(-1.2, 1.19999)

# also looking into phsd (despite 0 visible flow)
h_h_2d_phsd.GetXaxis().SetRangeUser(-1.6, -1.20001)
h_h_1d_left_deta = h_h_2d_phsd.ProjectionY("h_h_1d_left_deta")
h_h_2d_phsd.GetXaxis().SetRangeUser(1.2, 1.5999999)
h_h_1d_right_deta = h_h_2d_phsd.ProjectionY("h_h_1d_right_deta")
h_h_1d_large_deta = h_h_1d_left_deta.Clone("h_h_1d_large_deta")
h_h_1d_large_deta.Add(h_h_1d_right_deta)
vn_fit_phsd_string = "[0] + [1]*cos(2*x) + [2]*cos(4*x)"
vn_fit_phsd = rt.TF1("vn_fit_phsd", vn_fit_phsd_string, -rt.TMath.Pi()/2, rt.TMath.Pi()/2)
vn_fit_phsd_total = rt.TF1("vn_fit_phsd", vn_fit_phsd_string, -rt.TMath.Pi()/2, 3*rt.TMath.Pi()/2)
vn_fit_phsd.SetParameter(0, 0.03)
vn_fit_phsd.SetParameter(1, 0.0275)
vn_fit_phsd.FixParameter(2, 0.0)
h_h_1d_large_deta.Fit(vn_fit_phsd, "R")
vn_fit_phsd_total.SetParameter(0, vn_fit_phsd.GetParameter(0))
vn_fit_phsd_total.SetParameter(1, vn_fit_phsd.GetParameter(1))
vn_fit_phsd_total.SetParameter(2, vn_fit_phsd.GetParameter(2))
h_h_1d_large_deta.Draw()
vn_fit_phsd_total.Draw("same")
c.Draw()
c.SaveAs("figures/phsd_vn_fit_phsd.pdf")
# setting the dEta range back to normal
h_h_2d_phsd.GetXaxis().SetRangeUser(-1.2, 1.19999)

# also looking into data just to see what happens :D
h_h_2d_data.GetXaxis().SetRangeUser(-1.6, -1.20001)
h_h_1d_left_deta = h_h_2d_data.ProjectionY("h_h_1d_left_deta")
h_h_2d_data.GetXaxis().SetRangeUser(1.2, 1.5999999)
h_h_1d_right_deta = h_h_2d_data.ProjectionY("h_h_1d_right_deta")
h_h_1d_large_deta = h_h_1d_left_deta.Clone("h_h_1d_large_deta")
h_h_1d_large_deta.Add(h_h_1d_right_deta)
vn_fit_data_string = "[0] + [1]*cos(2*x) + [2]*cos(4*x)"
vn_fit_data = rt.TF1("vn_fit_data", vn_fit_data_string, -rt.TMath.Pi()/2, rt.TMath.Pi()/2)
vn_fit_data_total = rt.TF1("vn_fit_data", vn_fit_data_string, -rt.TMath.Pi()/2, 3*rt.TMath.Pi()/2)
vn_fit_data.SetParameter(0, 0.07)
vn_fit_data.SetParameter(1, 0.0275)
vn_fit_data.FixParameter(2, 0) # there is no v4 in data
h_h_1d_large_deta.Fit(vn_fit_data, "R")
vn_fit_data_total.SetParameter(0, vn_fit_data.GetParameter(0))
vn_fit_data_total.SetParameter(1, vn_fit_data.GetParameter(1))
vn_fit_data_total.SetParameter(2, vn_fit_data.GetParameter(2))
h_h_1d_large_deta.Draw()
vn_fit_data_total.Draw("same")
c.Draw()
c.SaveAs("figures/data_vn_fit_data.pdf")
# setting the dEta range back to normal
h_h_2d_data.GetXaxis().SetRangeUser(-1.2, 1.19999)


h_h_1d_data = h_h_2d_data.ProjectionY("h_h_1d_data")
h_h_1d_dpmjet = h_h_2d_dpmjet.ProjectionY("h_h_1d_dpmjet")
h_h_1d_epos = h_h_2d_epos.ProjectionY("h_h_1d_epos")
h_h_1d_phsd = h_h_2d_phsd.ProjectionY("h_h_1d_phsd")
h_lambda_1d_data = h_lambda_2d_data.ProjectionY("h_lambda_1d_data")
h_lambda_1d_dpmjet = h_lambda_2d_dpmjet.ProjectionY("h_lambda_1d_dpmjet")
h_lambda_1d_epos = h_lambda_2d_epos.ProjectionY("h_lambda_1d_epos")
h_lambda_1d_phsd = h_lambda_2d_phsd.ProjectionY("h_lambda_1d_phsd")

h_h_1d_data.SetLineColor(rt.kBlack)
h_h_1d_data.SetLineWidth(2)
h_h_1d_data.SetMarkerColor(rt.kBlack)
h_h_1d_data.SetMarkerStyle(20)
h_h_1d_data.SetMarkerSize(1.5)
h_h_1d_data.GetYaxis().SetRangeUser(0.8*h_h_1d_data.GetMinimum(), 1.3*h_h_1d_data.GetMaximum())
h_h_1d_dpmjet.SetLineColor(rt.kBlue + 2)
h_h_1d_dpmjet.SetLineWidth(2)
h_h_1d_dpmjet.SetMarkerColor(rt.kBlue + 2)
h_h_1d_dpmjet.SetMarkerStyle(20)
h_h_1d_dpmjet.SetMarkerSize(1.5)
h_h_1d_dpmjet.GetYaxis().SetRangeUser(0.8*h_h_1d_dpmjet.GetMinimum(), 1.3*h_h_1d_dpmjet.GetMaximum())
h_h_1d_epos.SetLineColor(rt.kGreen + 2)
h_h_1d_epos.SetLineWidth(2)
h_h_1d_epos.SetMarkerColor(rt.kGreen + 2)
h_h_1d_epos.SetMarkerStyle(20)
h_h_1d_epos.SetMarkerSize(1.5)
h_h_1d_epos.GetYaxis().SetRangeUser(0.8*h_h_1d_epos.GetMinimum(), 1.3*h_h_1d_epos.GetMaximum())
h_h_1d_phsd.SetLineColor(rt.kRed + 2)
h_h_1d_phsd.SetLineWidth(2)
h_h_1d_phsd.SetMarkerColor(rt.kRed + 2)
h_h_1d_phsd.SetMarkerStyle(20)
h_h_1d_phsd.SetMarkerSize(1.5)
h_h_1d_phsd.GetYaxis().SetRangeUser(0.8*h_h_1d_phsd.GetMinimum(), 1.3*h_h_1d_phsd.GetMaximum())

legend_1d = rt.TLegend(0.75, 0.75, 0.9, 0.87)
legend_1d.AddEntry(h_h_1d_data, "Data")
legend_1d.AddEntry(h_h_1d_dpmjet, "DPMJet")
legend_1d.AddEntry(h_h_1d_epos, "EPOS-LHC")
legend_1d.AddEntry(h_h_1d_phsd, "PHSD")
legend_1d.SetBorderSize(0)
legend_1d.SetFillStyle(0)
h_h_1d_data.GetYaxis().SetRangeUser(0.01, 0.5)
h_h_1d_data.Draw()
h_h_1d_epos.Draw("SAME")
h_h_1d_dpmjet.Draw("SAME")
h_h_1d_phsd.Draw("SAME")
legend_1d.Draw("SAME")
c.Draw()
c.SaveAs("figures/h_h_1d_model_comp.pdf")

# scale the vn fit function as the dEta bin width is different (EPOS only)
vn_fit_scale = 2.4/0.8
phsd_fit_scale = vn_fit_scale*0.944 # not doing mixed-event correction with PHSD, dEta is NOT flat at large dEta
vn_fit_epos_total.SetParameter(0, vn_fit_epos_total.GetParameter(0)*vn_fit_scale)
vn_fit_epos_total.SetParameter(1, vn_fit_epos_total.GetParameter(1)*vn_fit_scale)
vn_fit_epos_total.SetParameter(2, vn_fit_epos_total.GetParameter(2)*vn_fit_scale)
vn_fit_dpmjet_total.SetParameter(0, vn_fit_dpmjet_total.GetParameter(0)*vn_fit_scale)
vn_fit_dpmjet_total.SetParameter(1, vn_fit_dpmjet_total.GetParameter(1)*vn_fit_scale)
vn_fit_dpmjet_total.SetParameter(2, vn_fit_dpmjet_total.GetParameter(2)*vn_fit_scale)
vn_fit_phsd_total.SetParameter(0, vn_fit_phsd_total.GetParameter(0)*phsd_fit_scale)
vn_fit_phsd_total.SetParameter(1, vn_fit_phsd_total.GetParameter(1)*phsd_fit_scale)
vn_fit_phsd_total.SetParameter(2, vn_fit_phsd_total.GetParameter(2)*phsd_fit_scale)
vn_fit_data_total.SetParameter(0, vn_fit_data_total.GetParameter(0)*vn_fit_scale)
vn_fit_data_total.SetParameter(1, vn_fit_data_total.GetParameter(1)*vn_fit_scale)
vn_fit_data_total.SetParameter(2, vn_fit_data_total.GetParameter(2)*vn_fit_scale)
h_h_1d_data_subtracted = h_h_1d_data.Clone("h_h_1d_data_subtracted")
h_h_1d_data_subtracted.Add(vn_fit_data_total, -1)
h_h_1d_epos_subtracted = h_h_1d_epos.Clone("h_h_1d_epos_subtracted")
h_h_1d_epos_subtracted.Add(vn_fit_epos_total, -1)
h_h_1d_dpmjet_subtracted = h_h_1d_dpmjet.Clone("h_h_1d_dpmjet_subtracted")
h_h_1d_dpmjet_subtracted.Add(vn_fit_dpmjet_total, -1)
h_h_1d_phsd_subtracted = h_h_1d_phsd.Clone("h_h_1d_phsd_subtracted")
h_h_1d_phsd_subtracted.Add(vn_fit_phsd_total, -1)
legend_1d_subtracted = rt.TLegend(0.65, 0.75, 0.9, 0.87)
legend_1d_subtracted.AddEntry(h_h_1d_data, "Data (UE subtracted)")
legend_1d_subtracted.AddEntry(h_h_1d_dpmjet, "DPMJet (UE subtracted)")
legend_1d_subtracted.AddEntry(h_h_1d_epos, "EPOS-LHC (UE subtracted)")
legend_1d_subtracted.AddEntry(h_h_1d_phsd, "PHSD (UE subtracted)")
legend_1d_subtracted.SetBorderSize(0)
legend_1d_subtracted.SetFillStyle(0)
h_h_1d_data_subtracted.GetYaxis().SetRangeUser(-0.008, 0.2)
h_h_1d_data_subtracted.Draw()
h_h_1d_epos_subtracted.Draw("SAME")
h_h_1d_dpmjet_subtracted.Draw("SAME")
h_h_1d_phsd_subtracted.Draw("SAME")
legend_1d_subtracted.Draw("SAME")
c.Draw()
c.SaveAs("figures/h_h_1d_model_comp_ue_subtracted.pdf")

# fit the subtracted plots
von_fit_string = " + [0]/(2*TMath::Pi()*TMath::BesselI0([1]))*TMath::Exp([1]*TMath::Cos(x))"
von_fit_string += " + [2]/(2*TMath::Pi()*TMath::BesselI0([3]))*TMath::Exp([3]*TMath::Cos(x- TMath::Pi()))"

von_fit_data = rt.TF1("von_fit_data", von_fit_string, -rt.TMath.Pi()/2, 3*rt.TMath.Pi()/2)
von_fit_data.SetNpx(1000)
von_fit_data.SetLineColor(rt.kBlack)
von_fit_data.SetLineStyle(2)
von_fit_data.SetParameter(0, 0.01)
von_fit_data.SetParameter(1, 20)
von_fit_data.SetParLimits(1, 0, 100)
von_fit_data.SetParameter(2, 0.01)
von_fit_data.SetParameter(3, 20)
von_fit_data.SetParLimits(3, 0, 100)
h_h_1d_data_subtracted_with_fit = h_h_1d_data_subtracted.Clone("h_h_1d_data_subtracted_with_fit")
h_h_1d_data_subtracted_with_fit.Fit(von_fit_data, "R")

von_fit_epos = rt.TF1("von_fit_epos", von_fit_string, -rt.TMath.Pi()/2, 3*rt.TMath.Pi()/2)
von_fit_epos.SetNpx(1000)
von_fit_epos.SetLineColor(rt.kGreen + 2)
von_fit_epos.SetLineStyle(2)
von_fit_epos.SetParameter(0, 0.01)
von_fit_epos.SetParameter(1, 20)
von_fit_epos.SetParLimits(1, 0, 100)
von_fit_epos.SetParameter(2, 0.01)
von_fit_epos.SetParameter(3, 20)
von_fit_epos.SetParLimits(3, 0, 100)
h_h_1d_epos_subtracted.Fit(von_fit_epos, "R")

von_fit_dpmjet = rt.TF1("von_fit_dpmjet", von_fit_string, -rt.TMath.Pi()/2, 3*rt.TMath.Pi()/2)
von_fit_dpmjet.SetNpx(1000)
von_fit_dpmjet.SetLineColor(rt.kBlue + 2)
von_fit_dpmjet.SetLineStyle(2)
von_fit_dpmjet.SetParameter(0, 0.01)
von_fit_dpmjet.SetParameter(1, 20)
von_fit_dpmjet.SetParLimits(1, 0, 100)
von_fit_dpmjet.SetParameter(2, 0.01)
von_fit_dpmjet.SetParameter(3, 20)
von_fit_dpmjet.SetParLimits(3, 0, 100)
h_h_1d_dpmjet_subtracted.Fit(von_fit_dpmjet, "R")

von_fit_phsd = rt.TF1("von_fit_phsd", von_fit_string, -rt.TMath.Pi()/2, 3*rt.TMath.Pi()/2)
von_fit_phsd.SetNpx(1000)
von_fit_phsd.SetLineColor(rt.kRed + 2)
von_fit_phsd.SetLineStyle(2)
von_fit_phsd.SetParameter(0, 0.01)
von_fit_phsd.SetParameter(1, 20)
von_fit_phsd.SetParLimits(1, 0, 100)
von_fit_phsd.SetParameter(2, 0.01)
von_fit_phsd.SetParameter(3, 20)
von_fit_phsd.SetParLimits(3, 0, 100)
h_h_1d_phsd_subtracted.Fit(von_fit_phsd, "R")

legend_1d_subtracted = rt.TLegend(0.6, 0.65, 0.9, 0.87)
legend_1d_subtracted.AddEntry(h_h_1d_data, "Data (UE subtracted)", "lep")
legend_1d_subtracted.AddEntry(von_fit_dpmjet, "DPMJet", "l")
legend_1d_subtracted.AddEntry(von_fit_epos, "EPOS-LHC", "l")
legend_1d_subtracted.AddEntry(von_fit_phsd, "PHSD", "l")
legend_1d_subtracted.SetBorderSize(0)
legend_1d_subtracted.SetFillStyle(0)

h_h_1d_data_subtracted.GetYaxis().SetRangeUser(-0.008, 0.25)
h_h_1d_data_subtracted.Draw()
von_fit_data.Draw("SAME")
von_fit_epos.Draw("SAME")
von_fit_dpmjet.Draw("SAME")
von_fit_phsd.Draw("SAME")
legend_1d_subtracted.Draw("SAME")

c.Draw()
c.SaveAs("figures/h_h_1d_model_comp_ue_subtracted_with_fits.pdf")


h_h_data_near_kappa = von_fit_data.GetParameter(1)
h_h_data_near_kappa_error = von_fit_data.GetParError(1)
h_h_data_away_kappa = von_fit_data.GetParameter(3)
h_h_data_away_kappa_error = von_fit_data.GetParError(3)
h_h_data_near_width = get_width_from_kappa(h_h_data_near_kappa)
h_h_data_near_width_error = get_width_error_from_kappa(h_h_data_near_kappa, h_h_data_near_kappa_error)
h_h_data_away_width = get_width_from_kappa(h_h_data_away_kappa)
h_h_data_away_width_error = get_width_error_from_kappa(h_h_data_away_kappa, h_h_data_away_kappa_error)

h_h_epos_near_kappa = von_fit_epos.GetParameter(1)
h_h_epos_near_kappa_error = von_fit_epos.GetParError(1)
h_h_epos_away_kappa = von_fit_epos.GetParameter(3)
h_h_epos_away_kappa_error = von_fit_epos.GetParError(3)
h_h_epos_near_width = get_width_from_kappa(h_h_epos_near_kappa)
h_h_epos_near_width_error = get_width_error_from_kappa(h_h_epos_near_kappa, h_h_epos_near_kappa_error)
h_h_epos_away_width = get_width_from_kappa(h_h_epos_away_kappa)
h_h_epos_away_width_error = get_width_error_from_kappa(h_h_epos_away_kappa, h_h_epos_away_kappa_error)

h_h_dpmjet_near_kappa = von_fit_dpmjet.GetParameter(1)
h_h_dpmjet_near_kappa_error = von_fit_dpmjet.GetParError(1)
h_h_dpmjet_away_kappa = von_fit_dpmjet.GetParameter(3)
h_h_dpmjet_away_kappa_error = von_fit_dpmjet.GetParError(3)
h_h_dpmjet_near_width = get_width_from_kappa(h_h_dpmjet_near_kappa)
h_h_dpmjet_near_width_error = get_width_error_from_kappa(h_h_dpmjet_near_kappa, h_h_dpmjet_near_kappa_error)
h_h_dpmjet_away_width = get_width_from_kappa(h_h_dpmjet_away_kappa)
h_h_dpmjet_away_width_error = get_width_error_from_kappa(h_h_dpmjet_away_kappa, h_h_dpmjet_away_kappa_error)

h_h_phsd_near_kappa = von_fit_phsd.GetParameter(1)
h_h_phsd_near_kappa_error = von_fit_phsd.GetParError(1)
h_h_phsd_away_kappa = von_fit_phsd.GetParameter(3)
h_h_phsd_away_kappa_error = von_fit_phsd.GetParError(3)
h_h_phsd_near_width = get_width_from_kappa(h_h_phsd_near_kappa)
h_h_phsd_near_width_error = get_width_error_from_kappa(h_h_phsd_near_kappa, h_h_phsd_near_kappa_error)
h_h_phsd_away_width = get_width_from_kappa(h_h_phsd_away_kappa)
h_h_phsd_away_width_error = get_width_error_from_kappa(h_h_phsd_away_kappa, h_h_phsd_away_kappa_error)

width_plotting_hist = rt.TH1D("width_plotting_hist", "", 2, 0, 2)
width_plotting_hist.GetYaxis().SetTitle("Von Mises width")
width_plotting_hist.GetYaxis().SetTitleOffset(1.5)
width_plotting_hist.GetYaxis().SetTitleSize(0.05)
width_plotting_hist.GetXaxis().SetTitle("Jet region")
width_plotting_hist.GetXaxis().SetTitleOffset(1.5)
width_plotting_hist.GetXaxis().SetTitleSize(0.05)
width_plotting_hist.GetXaxis().SetBinLabel(1, "Near-side")
width_plotting_hist.GetXaxis().SetBinLabel(2, "Away-side")
width_plotting_hist.GetXaxis().SetLabelSize(0.05)

h_h_data_widths = rt.TH1D("h_h_data_widths", "", 2, 0, 2)
h_h_data_widths.SetMarkerStyle(20)
h_h_data_widths.SetMarkerSize(1.5)
h_h_data_widths.SetMarkerColor(rt.kBlack)
h_h_data_widths.SetLineColor(rt.kBlack)
h_h_data_widths.SetLineWidth(2)
h_h_data_widths.SetBinContent(1, h_h_data_near_width)
h_h_data_widths.SetBinError(1, h_h_data_near_width_error)
h_h_data_widths.SetBinContent(2, h_h_data_away_width)
h_h_data_widths.SetBinError(2, h_h_data_away_width_error)

h_h_dpmjet_widths = rt.TH1D("h_h_dpmjet_widths", "", 2, 0, 2)
h_h_dpmjet_widths.SetMarkerStyle(20)
h_h_dpmjet_widths.SetMarkerSize(1.5)
h_h_dpmjet_widths.SetMarkerColor(rt.kBlue + 2)
h_h_dpmjet_widths.SetLineColor(rt.kBlue + 2)
h_h_dpmjet_widths.SetLineWidth(2)
h_h_dpmjet_widths.SetBinContent(1, h_h_dpmjet_near_width)
h_h_dpmjet_widths.SetBinError(1, h_h_dpmjet_near_width_error)
h_h_dpmjet_widths.SetBinContent(2, h_h_dpmjet_away_width)
h_h_dpmjet_widths.SetBinError(2, h_h_dpmjet_away_width_error)

h_h_epos_widths = rt.TH1D("h_h_epos_widths", "", 2, 0, 2)
h_h_epos_widths.SetMarkerStyle(20)
h_h_epos_widths.SetMarkerSize(1.5)
h_h_epos_widths.SetMarkerColor(rt.kGreen + 2)
h_h_epos_widths.SetLineColor(rt.kGreen + 2)
h_h_epos_widths.SetLineWidth(2)
h_h_epos_widths.SetBinContent(1, h_h_epos_near_width)
h_h_epos_widths.SetBinError(1, h_h_epos_near_width_error)
h_h_epos_widths.SetBinContent(2, h_h_epos_away_width)
h_h_epos_widths.SetBinError(2, h_h_epos_away_width_error)

h_h_phsd_widths = rt.TH1D("h_h_phsd_widths", "", 2, 0, 2)
h_h_phsd_widths.SetMarkerStyle(20)
h_h_phsd_widths.SetMarkerSize(1.5)
h_h_phsd_widths.SetMarkerColor(rt.kRed + 2)
h_h_phsd_widths.SetLineColor(rt.kRed + 2)
h_h_phsd_widths.SetLineWidth(2)
h_h_phsd_widths.SetBinContent(1, h_h_phsd_near_width)
h_h_phsd_widths.SetBinError(1, h_h_phsd_near_width_error)
h_h_phsd_widths.SetBinContent(2, h_h_phsd_away_width)
h_h_phsd_widths.SetBinError(2, h_h_phsd_away_width_error)

width_plotting_hist.GetYaxis().SetRangeUser(0, 1)
width_plotting_hist.Draw()
h_h_data_widths.Draw("same")
h_h_dpmjet_widths.Draw("same")
h_h_epos_widths.Draw("same")
h_h_phsd_widths.Draw("same")

leg = rt.TLegend(0.2, 0.6, 0.5, 0.9)
leg.AddEntry(h_h_data_widths, "Data", "lep")
leg.AddEntry(h_h_dpmjet_widths, "DPMJET", "lep")
leg.AddEntry(h_h_epos_widths, "EPOS", "lep")
leg.AddEntry(h_h_phsd_widths, "PHSD", "lep")
leg.SetBorderSize(0)
leg.SetFillStyle(0)

leg.Draw()
c.SaveAs("figures/h_h_widths.pdf")


# doing our best to get the massive flow BG for EPOS-LHC
h_lambda_2d_epos.GetXaxis().SetRangeUser(-1.6, -1.20001)
h_lambda_1d_left_deta = h_lambda_2d_epos.ProjectionY("h_lambda_1d_left_deta")
h_lambda_2d_epos.GetXaxis().SetRangeUser(1.2, 1.5999999)
h_lambda_1d_right_deta = h_lambda_2d_epos.ProjectionY("h_lambda_1d_right_deta")
h_lambda_1d_large_deta = h_lambda_1d_left_deta.Clone("h_lambda_1d_large_deta")
h_lambda_1d_large_deta.Add(h_lambda_1d_right_deta)
vn_fit_epos_string = "[0] + [1]*cos(2*x) + [2]*cos(4*x)"
vn_fit_epos = rt.TF1("vn_fit_epos", vn_fit_epos_string, -rt.TMath.Pi()/2, rt.TMath.Pi()/2)
vn_fit_epos_total = rt.TF1("vn_fit_epos", vn_fit_epos_string, -rt.TMath.Pi()/2, 3*rt.TMath.Pi()/2)
vn_fit_epos.SetParameter(0, 0.051)
vn_fit_epos.SetParameter(1, 0.0275)
h_lambda_1d_large_deta.Fit(vn_fit_epos, "R")
vn_fit_epos_total.SetParameter(0, vn_fit_epos.GetParameter(0))
vn_fit_epos_total.SetParameter(1, vn_fit_epos.GetParameter(1))
vn_fit_epos_total.SetParameter(2, vn_fit_epos.GetParameter(2))
h_lambda_1d_large_deta.Draw()
vn_fit_epos_total.Draw("same")
c.Draw()
c.SaveAs("figures/h_lambda_vn_fit_epos.pdf")
# setting the dEta range back to normal
h_lambda_2d_epos.GetXaxis().SetRangeUser(-1.2, 1.19999)

# making sure DPMJet doesnt have flow
h_lambda_2d_dpmjet.GetXaxis().SetRangeUser(-1.6, -1.20001)
h_lambda_1d_left_deta = h_lambda_2d_dpmjet.ProjectionY("h_lambda_1d_left_deta")
h_lambda_2d_dpmjet.GetXaxis().SetRangeUser(1.2, 1.5999999)
h_lambda_1d_right_deta = h_lambda_2d_dpmjet.ProjectionY("h_lambda_1d_right_deta")
h_lambda_1d_large_deta = h_lambda_1d_left_deta.Clone("h_lambda_1d_large_deta")
h_lambda_1d_large_deta.Add(h_lambda_1d_right_deta)
vn_fit_dpmjet_string = "[0] + [1]*cos(2*x) + [2]*cos(4*x)"
vn_fit_dpmjet = rt.TF1("vn_fit_dpmjet", vn_fit_dpmjet_string, -rt.TMath.Pi()/2, rt.TMath.Pi()/2)
vn_fit_dpmjet_total = rt.TF1("vn_fit_dpmjet", vn_fit_dpmjet_string, -rt.TMath.Pi()/2, 3*rt.TMath.Pi()/2)
vn_fit_dpmjet.SetParameter(0, 0.051)
vn_fit_dpmjet.FixParameter(1, 0)
vn_fit_dpmjet.FixParameter(2, 0)
h_lambda_1d_large_deta.Fit(vn_fit_dpmjet, "R")
vn_fit_dpmjet_total.SetParameter(0, vn_fit_dpmjet.GetParameter(0))
vn_fit_dpmjet_total.SetParameter(1, vn_fit_dpmjet.GetParameter(1))
vn_fit_dpmjet_total.SetParameter(2, vn_fit_dpmjet.GetParameter(2))
h_lambda_1d_large_deta.Draw()
vn_fit_dpmjet_total.Draw("same")
c.Draw()
c.SaveAs("figures/h_lambda_vn_fit_dpmjet.pdf")
# setting the dEta range back to normal
h_lambda_2d_dpmjet.GetXaxis().SetRangeUser(-1.2, 1.19999)

# checking flow in data
h_lambda_2d_data.GetXaxis().SetRangeUser(-1.6, -1.20001)
h_lambda_1d_left_deta = h_lambda_2d_data.ProjectionY("h_lambda_1d_left_deta")
h_lambda_2d_data.GetXaxis().SetRangeUser(1.2, 1.5999999)
h_lambda_1d_right_deta = h_lambda_2d_data.ProjectionY("h_lambda_1d_right_deta")
h_lambda_1d_large_deta = h_lambda_1d_left_deta.Clone("h_lambda_1d_large_deta")
h_lambda_1d_large_deta.Add(h_lambda_1d_right_deta)
vn_fit_data_string = "[0] + [1]*cos(2*x) + [2]*cos(4*x)"
vn_fit_data = rt.TF1("vn_fit_data", vn_fit_data_string, -rt.TMath.Pi()/2, rt.TMath.Pi()/2)
vn_fit_data_total = rt.TF1("vn_fit_data", vn_fit_data_string, -rt.TMath.Pi()/2, 3*rt.TMath.Pi()/2)
vn_fit_data.FixParameter(0, 0.011)
vn_fit_data.SetParameter(1, 9e-4)
vn_fit_data.FixParameter(2, 0)
h_lambda_1d_large_deta.Fit(vn_fit_data, "R")
vn_fit_data_total.SetParameter(0, vn_fit_data.GetParameter(0))
vn_fit_data_total.SetParameter(1, vn_fit_data.GetParameter(1))
vn_fit_data_total.SetParameter(2, vn_fit_data.GetParameter(2))
h_lambda_1d_large_deta.Draw()
vn_fit_data_total.Draw("same")
c.Draw()
c.SaveAs("figures/h_lambda_vn_fit_data.pdf")
# setting the dEta range back to normal
h_lambda_2d_data.GetXaxis().SetRangeUser(-1.2, 1.19999)


h_lambda_1d_data.SetLineColor(rt.kBlack)
h_lambda_1d_data.SetLineWidth(2)
h_lambda_1d_data.SetMarkerColor(rt.kBlack)
h_lambda_1d_data.SetMarkerStyle(21)
h_lambda_1d_data.SetMarkerSize(1.5)
h_lambda_1d_data.GetYaxis().SetRangeUser(0.8*h_lambda_1d_data.GetMinimum(), 1.3*h_lambda_1d_data.GetMaximum())

h_lambda_1d_dpmjet.SetLineColor(rt.kBlue + 2)
h_lambda_1d_dpmjet.SetLineWidth(2)
h_lambda_1d_dpmjet.SetMarkerColor(rt.kBlue + 2)
h_lambda_1d_dpmjet.SetMarkerStyle(21)
h_lambda_1d_dpmjet.SetMarkerSize(1.5)
h_lambda_1d_dpmjet.GetYaxis().SetRangeUser(0.8*h_lambda_1d_dpmjet.GetMinimum(), 1.3*h_lambda_1d_epos.GetMaximum())

h_lambda_1d_epos.SetLineColor(rt.kGreen + 2)
h_lambda_1d_epos.SetLineWidth(2)
h_lambda_1d_epos.SetMarkerColor(rt.kGreen + 2)
h_lambda_1d_epos.SetMarkerStyle(21)
h_lambda_1d_epos.SetMarkerSize(1.5)
h_lambda_1d_epos.GetYaxis().SetRangeUser(0.8*h_lambda_1d_epos.GetMinimum(), 1.3*h_lambda_1d_epos.GetMaximum())

print(f"h-Lambda TOTAL INTEGRAL DATA/EPOS: {h_lambda_1d_data.Integral()/h_lambda_1d_epos.Integral()}")
print(f"h-Lambda TOTAL INTEGRAL DATA/DPMJET: {h_lambda_1d_data.Integral()/h_lambda_1d_dpmjet.Integral()}")

h_lambda_1d_phsd.SetLineColor(rt.kRed + 2)
h_lambda_1d_phsd.SetLineWidth(2)
h_lambda_1d_phsd.SetMarkerColor(rt.kRed + 2)
h_lambda_1d_phsd.SetMarkerStyle(21)
h_lambda_1d_phsd.SetMarkerSize(1.5)
h_lambda_1d_phsd.GetYaxis().SetRangeUser(0.8*h_lambda_1d_phsd.GetMinimum(), 1.3*h_lambda_1d_phsd.GetMaximum())

# normalize data and phsd for quick comparison
h_lambda_1d_data.Scale(1/h_lambda_1d_data.Integral())
h_lambda_1d_phsd.Scale(1/h_lambda_1d_phsd.Integral())

legend_1d = rt.TLegend(0.75, 0.75, 0.9, 0.87)
legend_1d.AddEntry(h_lambda_1d_data, "Data")
# legend_1d.AddEntry(h_lambda_1d_dpmjet, "DPMJet")
# legend_1d.AddEntry(h_lambda_1d_epos, "EPOS-LHC")
legend_1d.AddEntry(h_lambda_1d_phsd, "PHSD")
legend_1d.SetBorderSize(0)
legend_1d.SetFillStyle(0)
h_lambda_1d_data.GetYaxis().SetRangeUser(0.03, 0.1)
h_lambda_1d_data.Draw()
# h_lambda_1d_epos.Draw("SAME")
# h_lambda_1d_dpmjet.Draw("SAME")
h_lambda_1d_phsd.Draw("SAME")
legend_1d.Draw("SAME")
c.Draw()
c.SaveAs("figures/h_lambda_1d_model_comp_phsd_normalized.pdf")

# scale the vn fit function as the dEta bin width is different (EPOS only)
vn_fit_scale = 2.4/0.8
test_epos_scale = vn_fit_scale*1.33
phsd_fit_scale = vn_fit_scale*0.944 # not doing mixed-event correction with PHSD, dEta is NOT flat at large dEta

vn_fit_epos_total.SetParameter(0, vn_fit_epos_total.GetParameter(0)*test_epos_scale)
vn_fit_epos_total.SetParameter(1, vn_fit_epos_total.GetParameter(1)*test_epos_scale)
vn_fit_epos_total.SetParameter(2, vn_fit_epos_total.GetParameter(2)*test_epos_scale)

vn_fit_dpmjet_total.SetParameter(0, vn_fit_dpmjet_total.GetParameter(0)*vn_fit_scale)
vn_fit_dpmjet_total.SetParameter(1, vn_fit_dpmjet_total.GetParameter(1)*vn_fit_scale)
vn_fit_dpmjet_total.SetParameter(2, vn_fit_dpmjet_total.GetParameter(2)*vn_fit_scale)

vn_fit_phsd_total.SetParameter(0, vn_fit_phsd_total.GetParameter(0)*phsd_fit_scale)
vn_fit_phsd_total.SetParameter(1, vn_fit_phsd_total.GetParameter(1)*phsd_fit_scale)
vn_fit_phsd_total.SetParameter(2, vn_fit_phsd_total.GetParameter(2)*phsd_fit_scale)

vn_fit_data_total = rt.TF1("vn_fit_data_total", "[0]*(1 + 2*([1]*[2]*cos(2*x)))", -rt.TMath.Pi()/2, 3*rt.TMath.Pi()/2)
vn_fit_data_total.SetParameter(0, 0.032456)
vn_fit_data_total.SetParameter(1, 0.0874)
vn_fit_data_total.SetParameter(2, 0.10545)

h_lambda_1d_data_subtracted = h_lambda_1d_data.Clone("h_lambda_1d_data_subtracted")
h_lambda_1d_data.Draw()
vn_fit_data_total.Draw("SAME")
c.Draw()
c.SaveAs("test.pdf")
h_lambda_1d_data_subtracted.Add(vn_fit_data_total, -1)

h_lambda_1d_epos_subtracted = h_lambda_1d_epos.Clone("h_lambda_1d_epos_subtracted")
h_lambda_1d_epos_subtracted.Add(vn_fit_epos_total, -1)

h_lambda_1d_dpmjet_subtracted = h_lambda_1d_dpmjet.Clone("h_lambda_1d_dpmjet_subtracted")
h_lambda_1d_dpmjet_subtracted.Add(vn_fit_dpmjet_total, -1)

h_lambda_1d_phsd_subtracted = h_lambda_1d_phsd.Clone("h_lambda_1d_phsd_subtracted")
h_lambda_1d_phsd_subtracted.Add(vn_fit_phsd_total, -1)

legend_1d_subtracted = rt.TLegend(0.65, 0.75, 0.9, 0.87)
legend_1d_subtracted.AddEntry(h_lambda_1d_data, "Data (UE subtracted)")
legend_1d_subtracted.AddEntry(h_lambda_1d_dpmjet, "DPMJet (UE subtracted)")
legend_1d_subtracted.AddEntry(h_lambda_1d_epos, "EPOS-LHC (UE subtracted)")
legend_1d_subtracted.AddEntry(h_lambda_1d_phsd, "PHSD (UE subtracted)")
legend_1d_subtracted.SetBorderSize(0)
legend_1d_subtracted.SetFillStyle(0)
h_lambda_1d_data_subtracted.GetYaxis().SetRangeUser(-0.001, 0.016)
h_lambda_1d_data_subtracted.Draw()
h_lambda_1d_epos_subtracted.Draw("SAME")
h_lambda_1d_dpmjet_subtracted.Draw("SAME")
h_lambda_1d_phsd_subtracted.Draw("SAME")
legend_1d_subtracted.Draw("SAME")
c.Draw()
c.SaveAs("figures/h_lambda_1d_model_comp_ue_subtracted.pdf")